### ISSUE TITLE
Recruiting a Github/Data Analysis Facilitator for BC UMSC

### ISSUE THREAD

**Issue by lfunderburk** [lfunderburk/BC-UMSC-Workshops#1]
Hello @dfornika, 

We had an opportunity to meet during one of the organizing meetings for Hackseq. 

I am currently co-organizing SciProg along with the BC UMSC (BC Undergraduate Math and Stats Conference). BC UMSC's main purpose is to facilitate learning experiences and networking for senior students in math and stats. The main theme includes drawing connections between STEM fields, Data Analysis, Math and Stats. We will facilitate a number of workshops in R, Python, Github and Data Analysis. 

Given your experience, I was wondering if you would be interested in facilitating either the Introduction to Github or the Introduction to Data Analysis workshops. The conference will take place between April 25-27 2019. 

Refer to https://github.com/lfunderburk/BC-UMSC-Workshops for details on the conference. 

Let me know if this is something you would be interested in being a part of. Thank you for your time. 

Best,

Laura Gutierrez Funderburk (@lfunderburk )

**Comment by dfornika** [comment]
Hi Laura. Thanks for thinking of me for this role. Yes, I'd be interested in facilitating the Intro to GitHub workshop. I'll follow up soon by email to get a few more details.

**Comment by lfunderburk** [comment]
Thank you @dfornika . My email address is lgutierr@sfu.ca, I would be happy to answer any questions you have. I look forward to talking with you soon!
